libs/frontend/feature-build-event/src/lib/use-build-event.ts

[#828](https://github.com/samatechtw/pubstudio/issues/828)

fix: editor invalid state

---

libs/frontend/feature-build/src/components/StyleMenuEdit.vue
libs/frontend/feature-build/src/components/build-render/ProseMirrorEditor.vue
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-build/src/lib/use-reusable-style-menu.ts
libs/frontend/feature-color-picker/src/components/ColorPicker.vue
libs/frontend/feature-render/src/lib/get-reusable-style.ts
libs/frontend/feature-render/src/lib/use-render.ts
libs/shared/type-site/src/lib/i-style.ts

[#853](https://github.com/samatechtw/pubstudio/issues/853)
[#855](https://github.com/samatechtw/pubstudio/issues/855)
[#870](https://github.com/samatechtw/pubstudio/issues/870)
[#871](https://github.com/samatechtw/pubstudio/issues/871)

fix: reusable styles inheritance

---

apps/api-site-test/test/integration/get-site.spec.ts
backend/lib-shared-types/src/dto/site_api/get_site_dto.rs
backend/site-api/src/app/site/get_site.rs
libs/frontend/data-access-api/src/lib/api-local-site.ts
libs/frontend/data-access-site-api/src/lib/api-site.ts
libs/frontend/feature-build/src/components/preview/SitePreview.vue
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-site-store/src/lib/use-api-store.ts
libs/frontend/feature-site-store/src/lib/use-site-source.ts
libs/frontend/util-api/src/lib/api.ts
libs/frontend/util-site-deserialize/src/lib/deserialize-site.ts
libs/frontend/util-site-store/src/lib/serialize-site.ts
libs/shared/type-api-local-site/src/index.ts
libs/shared/type-api-local-site/src/lib/i-get-local-site-api-request.ts
libs/shared/type-api-site-sites/src/index.ts
libs/shared/type-api-site-sites/src/lib/i-get-site-api-request.ts
libs/shared/type-api-site-sites/src/lib/i-site.view-model.ts
libs/shared/type-site-store/src/lib/i-site-store.ts
libs/shared/type-site-store/src/lib/i-stored-site.ts
libs/shared/type-site/src/lib/i-site.ts
libs/shared/util-fetch-api/src/lib/default-response-interceptors.ts

Close https://github.com/samatechtw/pubstudio/issues/857

feat(site-api): get site add update key query

---

libs/frontend/feature-build/src/components/ComponentTreeItem.vue
libs/frontend/feature-build/src/lib/dnd/builder-dnd-component.ts
libs/frontend/feature-build/src/lib/dnd/drag-drop.ts
libs/frontend/feature-build/src/lib/dnd/row-layout.ts
libs/frontend/feature-build/src/lib/dnd/use-drag-drop.ts

[#854](https://github.com/samatechtw/pubstudio/issues/854)
[#864](https://github.com/samatechtw/pubstudio/issues/864)

fix: cannot drop component above container in component tree

---

libs/frontend/feature-command/src/lib/component/add-component.ts
libs/frontend/util-builtin/src/lib/components/builtin-header.ts
libs/frontend/util-builtin/src/lib/components/builtin-nav-menu.ts
libs/frontend/util-component/src/lib/detach-component.ts
libs/shared/type-site/src/lib/i-resolved-component-props.ts

fix: builtin header component link bug #873

---

libs/frontend/feature-build/src/lib/use-build.ts

feat: include name with pasted component #17

---

libs/frontend/feature-build/src/lib/dnd/builder-dnd-component.ts

[#860](https://github.com/samatechtw/pubstudio/issues/860)

fix: image with non-zero margin shifts on hover

---

libs/frontend/feature-build/src/components/build-render/ProseMirrorEditor.vue
libs/frontend/feature-build/src/components/toolbar/ToolbarText.vue
libs/frontend/feature-build/src/lib/use-toolbar-font-size.ts
libs/frontend/ui-widgets/src/lib/form/PSInput.vue
libs/frontend/util-gradient/src/lib/parse-gradients.ts

[ #874](https://github.com/samatechtw/pubstudio/issues/874)

fix: text gradient color missing in prosemirror editor

---

backend/lib-shared-site-api/src/db/sites_seed_data.rs

Close https://github.com/samatechtw/pubstudio/issues/891

feat(site-api): adjust the logic for create new charge #891

---

libs/shared/type-site/src/lib/enum-css.ts

feat: add line-height css #18

---

libs/frontend/feature-build/src/components/StyleRow.vue
libs/frontend/feature-build/src/components/build-render/ProseMirrorEditor.vue
libs/frontend/ui-theme/src/css/components/menu.postcss

[#861](https://github.com/samatechtw/pubstudio/issues/861)
[#877](https://github.com/samatechtw/pubstudio/issues/877)

feat: strip formatting when pasting into prosemirror editor

---

libs/frontend/feature-build/src/components/MenuRow.vue
libs/frontend/feature-build/src/components/MenuRowEdit.vue
libs/frontend/feature-build/src/components/StyleMenuEdit.vue
libs/frontend/feature-build/src/components/StyleRow.vue
libs/frontend/feature-build/src/components/component-menu/ComponentRole.vue
libs/frontend/feature-build/src/components/component-menu/ComponentStyles.vue
libs/frontend/feature-build/src/components/component-menu/ComponentTag.vue
libs/frontend/feature-build/src/components/theme-menu/ThemeVariableEdit.vue
libs/frontend/feature-site-store/src/lib/use-api-store.ts
libs/frontend/ui-widgets/src/lib/StyleProperty.vue

Close https://github.com/samatechtw/pubstudio/issues/879

feat: improve editor input auto focusing

---

libs/frontend/feature-site-assets/src/components/CreateAssetModal.vue

Close https://github.com/samatechtw/pubstudio/issues/884

feat: clear asset info in modal after upload

---

libs/frontend/feature-build/src/components/build-menu/BuildMenuAsset.vue
libs/frontend/feature-site-assets/src/components/AssetCard.vue
libs/frontend/feature-site-assets/src/lib/use-site-assets.ts

Close https://github.com/samatechtw/pubstudio/issues/878

fix: asset menu nt refreshed after upload

---

backend/lib-shared-types/src/shared/site.rs

https://github.com/samatechtw/pubstudio/pull/907

feat(site-api): print logs in jobs #904

---

docs/site-data-format.md
libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/feature-build/src/components/ComponentTreeItem.vue
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-command/src/lib/component-custom-style/set-component-custom-style.ts
libs/frontend/feature-command/src/lib/component-event/set-component-event.ts
libs/frontend/feature-command/src/lib/component-input/set-component-input.ts
libs/frontend/feature-command/src/lib/component-mixin/add-component-mixin.ts
libs/frontend/feature-command/src/lib/component-mixin/remove-component-mixin.ts
libs/frontend/feature-command/src/lib/component-mixin/replace-component-mixin.ts
libs/frontend/feature-command/src/lib/component-style/merge-component-style.ts
libs/frontend/feature-command/src/lib/component/add-component.ts
libs/frontend/feature-command/src/lib/component/edit-component.ts
libs/frontend/feature-command/src/lib/component/remove-component.spec.ts
libs/frontend/feature-command/src/lib/component/remove-component.ts
libs/frontend/feature-command/src/lib/move-component/move-component.ts
libs/frontend/feature-command/src/lib/page/add-page.ts
libs/frontend/feature-command/src/lib/page/change-page.spec.ts
libs/frontend/feature-command/src/lib/page/change-page.ts
libs/frontend/feature-command/src/lib/page/remove-page.ts
libs/frontend/feature-editor/src/lib/editor-helpers.ts
libs/frontend/util-test-mock/src/lib/mock-site-data.ts
libs/shared/type-command-data/src/lib/i-move-component-data.ts

feat: scroll to affeced component on undo/redo

---

libs/frontend/feature-build/src/components/FontFamily.vue
libs/frontend/feature-build/src/components/StyleRow.vue
libs/frontend/feature-build/src/components/theme-menu/GoogleFontSelect.vue
libs/frontend/feature-build/src/components/theme-menu/ThemeFontEdit.vue
libs/frontend/feature-build/src/components/theme-menu/ThemeFonts.vue
libs/frontend/feature-build/src/components/toolbar/StyleToolbar.vue
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-builtin/src/lib/behaviors.ts
libs/frontend/ui-widgets/src/lib/form/PSMultiselect.vue
libs/frontend/util-ids/src/lib/builtin-ids.ts

feat: font previous in theme menu and style toolbar #49

---

libs/frontend/feature-build/src/components/BuildContent.vue
libs/frontend/feature-build/src/components/BuildDndOverlay.vue
libs/frontend/feature-build/src/components/ComponentTreeItem.vue
libs/frontend/feature-build/src/components/build-menu/NewComponent.vue
libs/frontend/feature-build/src/lib/dnd/builder-dnd-component.ts
libs/frontend/feature-build/src/lib/dnd/builder-dnd.ts
libs/frontend/feature-build/src/lib/dnd/drag-drop.ts
libs/frontend/feature-build/src/lib/dnd/row-layout.ts
libs/frontend/feature-build/src/lib/dnd/use-drag-drop.ts
libs/frontend/feature-build/src/lib/render-builder.ts
libs/frontend/feature-site-assets/src/components/AssetCard.vue
libs/frontend/util-runtime/src/lib/runtime-context.ts

[#866](https://github.com/samatechtw/pubstudio/issues/866)
Hi @sampullman 
Except for the builder D&D "shaking" on hover issue, I also tried to fix the issue where we can't drop a component on root component in this PR.

866 cannot drop component at bottom bug

---

libs/frontend/ui-widgets/src/lib/InfoBubble.vue
libs/frontend/util-component/src/lib/compute-component-flattened-styles.ts

fix: css pseudostyle editor bug

---

apps/web-site/src/app/App.vue
libs/frontend/feature-build/src/components/StyleMenuList.vue
libs/frontend/feature-build/src/components/StyleRow.vue
libs/frontend/feature-build/src/components/build-render/ProseMirrorEditor.vue
libs/frontend/feature-build/src/components/component-menu/ComponentTabInfo.vue
libs/frontend/feature-build/src/components/component-menu/SvgEditModal.vue
libs/frontend/feature-build/src/components/page-menu/PageMenu.vue
libs/frontend/feature-build/src/components/page-menu/PageMeta.vue
libs/frontend/feature-build/src/components/preview/SitePreview.vue
libs/frontend/feature-build/src/components/theme-menu/ThemeMeta.vue
libs/frontend/feature-build/src/components/theme-menu/ThemeMetaEditModal.vue
libs/frontend/feature-build/src/components/theme-menu/ThemeMetaHead.vue
libs/frontend/feature-build/src/components/theme-menu/ThemeMetaHeadRow.vue
libs/frontend/feature-build/src/components/theme-menu/i-theme-meta-edit-data.ts
libs/frontend/feature-build/src/lib/create-code-editor-view.ts
libs/frontend/feature-build/src/lib/create-editor-view.ts
libs/frontend/feature-build/src/lib/dnd/row-layout.ts
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-command/src/lib/command.ts
libs/frontend/feature-command/src/lib/defaults/set-defaults-head.spec.ts
libs/frontend/feature-command/src/lib/page/set-page-head.spec.ts
libs/frontend/feature-command/src/lib/page/set-page-head.ts
libs/frontend/feature-render/src/lib/use-render.ts
libs/frontend/feature-site-store/src/lib/use-api-store.ts
libs/frontend/feature-site-translations/src/lib/use-site-translations.ts
libs/frontend/ui-theme/src/css/components/menu.postcss
libs/frontend/util-edit-text/src/lib/prosemirror-setup.ts
libs/frontend/util-edit-text/src/lib/schema-basic.ts
libs/shared/type-command-data/src/lib/i-set-page-head-data.ts
libs/shared/type-site/src/lib/i-head.ts

Close #46 
[#900](https://github.com/samatechtw/pubstudio/issues/900)

46 set custom page title

---

libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/feature-build-event/src/lib/util-build-event.ts
libs/frontend/feature-build/src/components/StyleMenuEdit.vue
libs/frontend/feature-build/src/components/StyleRow.vue
libs/frontend/feature-build/src/components/build-menu/BuildMenu.vue
libs/frontend/feature-build/src/components/build-menu/BuildMenuAsset.vue
libs/frontend/feature-build/src/components/component-menu/ComponentChildStyles.vue
libs/frontend/feature-build/src/components/component-menu/ComponentStyles.vue
libs/frontend/feature-build/src/components/component-menu/ComponentTabStyle.vue
libs/frontend/feature-build/src/lib/use-reusable-style-menu.ts
libs/frontend/ui-widgets/src/lib/StyleValue.vue
libs/frontend/ui-widgets/src/lib/form/PSMultiselect.vue
libs/frontend/ui-widgets/src/lib/modal/Modal.vue
libs/frontend/util-builtin/src/lib/components/builtin-text.ts

fix: various ux and css issues #87

---

apps/builder-demo/subset.config.js
apps/web-site/subset.config.js
libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/feature-build-event/src/lib/util-resize.ts
libs/frontend/feature-build/src/lib/dnd/builder-dnd-component.ts
tools/scripts/package-subset-module.js
tools/scripts/package-subset.js

fix: image hover after resize bug

---

libs/frontend/feature-build/src/components/MenuRow.vue
libs/frontend/feature-build/src/components/StyleRow.vue
libs/frontend/feature-build/src/components/component-menu/ComponentChildStyles.vue
libs/frontend/feature-build/src/components/component-menu/ComponentInputRow.vue
libs/frontend/feature-build/src/components/component-menu/ComponentInputs.vue
libs/frontend/feature-build/src/components/component-menu/ComponentMenu.vue
libs/frontend/feature-build/src/components/component-menu/ComponentStyles.vue
libs/frontend/feature-site-assets/src/components/SelectAssetModal.vue
libs/frontend/feature-site-assets/src/index.ts
libs/shared/type-api-platform-site-asset/src/lib/i-site-asset.view-model.ts

feat: select asset as src of image component

---

apps/web-site/src/app/App.vue
libs/frontend/feature-build/src/components/StyleMenuEdit.vue
libs/frontend/feature-build/src/components/build-render/ProseMirrorEditor.vue
libs/frontend/feature-build/src/components/preview/SitePreview.vue
libs/frontend/feature-build/src/lib/dnd/builder-dnd-component.ts
libs/frontend/feature-build/src/lib/render-builder.ts
libs/frontend/ui-theme/src/css/components/prosemirror-view.postcss
libs/frontend/util-edit-text/src/lib/prosemirror-setup.ts

fix: prosemirror component empty bug

---

apps/builder-demo/src/app/components/ExampleBuilder.vue
apps/builder-demo/src/translations/en.json
libs/frontend/feature-color-picker/src/components/ColorPicker.vue
libs/frontend/feature-command/src/lib/component-override-style/remove-component-override-style.ts

fix: color selector saturation reset bug #109

---

apps/builder-demo/src/app/components/ExampleBuilder.vue
apps/builder-demo/src/translations/en.json
libs/frontend/feature-build/src/components/toolbar/ToolbarText.vue
libs/frontend/feature-build/src/lib/use-toolbar-font-size.ts
libs/frontend/feature-build/src/lib/use-toolbar.ts
libs/frontend/feature-color-picker/src/components/ColorPicker.vue
libs/frontend/feature-command/src/lib/component-override-style/remove-component-override-style.ts

110 font size units

---

libs/frontend/feature-build/src/components/build-menu/BuildMenu.vue
libs/frontend/feature-build/src/components/build-render/ProseMirrorEditor.vue
libs/frontend/feature-build/src/lib/dnd/use-drag-drop.ts

feat: hide new component menu when dragging

---

apps/builder-demo/src/app/components/ExampleBuilder.vue
apps/builder-demo/src/translations/en.json
libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/feature-build/src/components/component-menu/ComponentChildStyles.vue
libs/frontend/feature-build/src/components/component-menu/ComponentDimensions.vue
libs/frontend/feature-build/src/components/component-menu/ComponentMenu.vue
libs/frontend/feature-build/src/components/component-menu/ComponentStyles.vue
libs/frontend/feature-build/src/components/component-menu/PaddingMarginEdit.vue
libs/frontend/feature-build/src/components/component-menu/SizeInput.vue
libs/frontend/feature-build/src/components/toolbar/ToolbarContainer.vue
libs/frontend/feature-editor/src/lib/editor-helpers.ts
libs/frontend/util-build/src/lib/create-site.ts
libs/frontend/util-site-deserialize/src/lib/deserialize-site.ts
libs/frontend/util-site-store/src/lib/serialize-site.ts
libs/frontend/util-test-mock/src/lib/mock-site-data.ts
libs/shared/type-site/src/lib/i-editor-context.ts

feat: move margin padding menu to right menu

---

libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/feature-build/src/components/ComponentTreeItem.vue
libs/frontend/feature-build/src/components/ComponentTreeItemRename.vue
libs/frontend/ui-widgets/src/lib/form/PSInput.vue
libs/frontend/util-runtime/src/lib/runtime-context.ts

feat: press enter to rename component in tree

---

libs/frontend/feature-build-event/src/lib/select-component.ts
libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/util-key-listener/src/lib/enum-keys.ts

feat: tab and shift tab to change selection

---

libs/frontend/feature-build/src/lib/use-toolbar.ts
libs/frontend/feature-color-picker/src/components/ColorPicker.vue
libs/frontend/feature-color-picker/src/lib/color-picker-util.ts
libs/frontend/feature-color-picker/src/lib/use-gradient.ts
libs/frontend/ui-build/src/components/toolbar/ToolbarColorPicker.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarContainer.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarText.vue

feat: colorpicker clear color and bug fixes #123

---

apps/builder-demo/src/translations/en.json
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-build/src/lib/use-copy-paste.ts
libs/frontend/feature-command/src/lib/apply-command.ts
libs/frontend/feature-command/src/lib/component/remove-component.ts
libs/frontend/feature-command/src/lib/component/replace-page-root.spec.ts
libs/frontend/feature-command/src/lib/component/replace-page-root.ts
libs/frontend/feature-command/src/lib/undo-command.ts
libs/frontend/ui-build/src/components/component-menu/ComponentMenu.vue
libs/frontend/util-command/src/lib/make-remove-component-data.ts
libs/shared/type-command-data/src/lib/i-replace-page-root-data.ts
libs/shared/type-command/src/lib/command-type.ts

feat: copy root component

---

libs/frontend/ui-build/src/components/ComponentTree.vue

fix: component tree child padding bug

---

libs/frontend/feature-build/src/lib/code-editor-plugins.ts
libs/frontend/feature-build/src/lib/create-code-editor-view.ts

fix: behavior modal javascript highlighting bug

---

apps/builder-demo/src/app/components/ExampleBuilder.vue
libs/frontend/feature-build/src/lib/use-page-menu.ts
libs/frontend/ui-build/src/components/build-menu/BuildMenu.vue
libs/frontend/ui-build/src/components/build-menu/BuildMenuPage.vue
libs/frontend/ui-build/src/components/page-menu/PageMenuView.vue
libs/frontend/ui-build/src/components/toolbar/StyleToolbar.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarPage.vue
libs/frontend/ui-theme/src/css/components/multiselect.postcss
libs/frontend/ui-widgets/src/lib/form/PSMultiselect.vue
libs/shared/type-site/src/lib/i-editor-context.ts

feat: style toolbar page dropdown

---

.eslintrc.json
libs/frontend/feature-build/src/lib/use-toolbar.ts
libs/frontend/ui-build/src/components/toolbar/ToolbarColorPicker.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarContainer.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarText.vue
libs/frontend/ui-build/src/components/toolbar/i-toolbar-color-picker.ts
libs/frontend/ui-widgets/src/lib/toolbar/ToolbarItem.vue

fix: color picker bug #149

---

libs/frontend/feature-build/src/lib/use-edit-component-styles.ts
libs/frontend/ui-build/src/components/component-menu/ComponentChildStyles.vue
libs/frontend/ui-widgets/src/lib/form/PSMultiselect.vue
libs/frontend/util-render/src/lib/util-render.ts

feat: component css property ordering

---

apps/builder-demo/src/translations/en.json
libs/frontend/feature-render-builder/src/components/LinkTooltip.vue
libs/frontend/util-tooltip/src/lib/use-tooltip.ts

feat: ui for setting link target _blank

---

libs/frontend/feature-preview/src/lib/preview-component.ts
libs/frontend/feature-render/src/lib/live-component.ts
libs/frontend/util-router/src/components/RouterLink.vue

fix: links not working in live site #167

---

libs/frontend/feature-build/src/lib/use-edit-component-styles.ts
libs/frontend/feature-build/src/lib/use-reusable-style-menu.ts
libs/frontend/ui-build/src/components/StyleMenuEdit.vue
libs/frontend/ui-build/src/components/StyleRow.vue
libs/frontend/ui-build/src/components/component-menu/ChildStyleRow.vue
libs/frontend/ui-build/src/components/component-menu/ComponentChildStyles.vue
libs/frontend/ui-build/src/components/component-menu/ComponentStyles.vue
libs/frontend/ui-widgets/src/lib/StyleProperty.vue
libs/frontend/ui-widgets/src/lib/StyleValue.vue
libs/shared/type-site/src/lib/i-style.ts

fix: component style undo bug #163

---

libs/frontend/feature-build-event/src/lib/util-build-event.ts
libs/frontend/ui-build/src/components/component-menu/SizeInput.vue
libs/frontend/ui-widgets/src/lib/ImagePlaceholder.vue
libs/frontend/ui-widgets/src/lib/StyleValue.vue

fix: editor bugs 231228 #175

---

libs/frontend/feature-build/src/lib/style/set-style-helpers.ts
libs/frontend/ui-build/src/components/theme-menu/ThemeMetaFavicon.vue

fix: favicon and style save bugs #176 #178

---

libs/frontend/feature-color-picker/src/components/ColorPicker.vue
libs/frontend/feature-site-assets/src/components/AssetsHeader.vue
libs/frontend/ui-build/src/components/build-menu/BuildMenuAsset.vue
libs/frontend/ui-widgets/src/lib/svg/Plus.vue

Close #181 
The actual fix is a single line change in the pubstudio repo.

fix: various ui fixes

---

.github/workflows/pr-commit.yml
.github/workflows/pr-merge-main.yml
.github/workflows/pr-merge-prod.yml
apps/api-site-test/test/integration/create-site.spec.ts
apps/api-site-test/test/integration/update-site.spec.ts
apps/builder-demo/src/translations/en.json
backend/lib-shared-site-api/src/db/sites_seed_data.rs
backend/lib-shared-types/src/dto/site_api/create_site_dto.rs
backend/lib-shared-types/src/dto/site_api/update_site_dto.rs
backend/lib-shared-types/src/type_util.rs
libs/frontend/feature-preview/src/lib/preview-component.ts
libs/frontend/feature-site-source/src/lib/computed-breakpoints.ts
libs/frontend/feature-sites/src/lib/use-sites.ts
libs/frontend/ui-widgets/src/lib/InfoBubble.vue
libs/frontend/ui-widgets/src/lib/form/PSInput.vue
libs/frontend/util-builtin/src/lib/resolve-behavior.ts
libs/frontend/util-builtin/src/lib/resolve-component.ts
libs/frontend/util-builtin/src/lib/resolve-style.ts
libs/frontend/util-builtin/src/lib/resolve-util.ts
libs/frontend/util-render/src/index.ts
libs/frontend/util-render/src/lib/sort-breakpoint-fn.ts
libs/frontend/util-render/src/lib/util-render.ts
libs/frontend/util-router/src/components/RouterLink.vue
libs/frontend/util-site-deserialize/src/index.ts
libs/frontend/util-site-deserialize/src/lib/deserialize-site.ts
libs/frontend/util-site-deserialize/src/lib/replace-namespace.ts

187 template site

---

libs/frontend/util-edit-text/src/lib/text-to-link-keymap.ts

fix: prosemirror link creation removes text bug #185

---

apps/api-site-test/test/integration/update-site.spec.ts
backend/lib-shared-types/src/dto/site_api/update_site_dto.rs
backend/lib-shared-types/src/error/api_error.rs
backend/site-api/src/app/site/update_site.rs
backend/site-api/src/db/site_repo.rs
libs/shared/type-api-site-sites/src/lib/i-update-site-api-request.ts

Close https://github.com/samatechtw/pubstudio/issues/937

feat(site-api): warn user if editor is open in another window #937

---

libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts
libs/frontend/ui-build/src/components/component-menu/ComponentDimensions.vue
libs/frontend/ui-build/src/components/component-menu/SizeInput.vue
libs/frontend/util-edit-text/src/lib/prosemirror-setup.ts
libs/frontend/util-runtime/src/lib/runtime-context.ts

fix: tab to select next component

---

apps/api-site-test/test/integration/get-site.spec.ts
apps/api-site-test/test/integration/update-site.spec.ts
backend/lib-shared-types/src/dto/site_api/get_site_dto.rs
backend/lib-shared-types/src/type_util.rs
backend/site-api/src/app/site/get_site.rs

fix: update_key date format incompatible #200

---

libs/frontend/feature-build/src/lib/style/use-reusable-style-menu.ts
libs/frontend/ui-build/src/components/FontFamily.vue
libs/frontend/ui-theme/src/css/layout.postcss
libs/frontend/ui-widgets/src/lib/IconTooltip.vue
libs/frontend/ui-widgets/src/lib/IconTooltipDelay.vue
libs/frontend/ui-widgets/src/lib/InfoBubble.vue
libs/frontend/ui-widgets/src/lib/hud/AppHUD.vue
libs/frontend/ui-widgets/src/lib/modal/Modal.vue
libs/frontend/ui-widgets/src/lib/toast/AppToast.vue
libs/frontend/ui-widgets/src/lib/toolbar/ToolbarItemDropdown.vue
libs/frontend/util-tooltip/src/lib/use-tooltip.ts

209 tooltip behind modal

---

libs/frontend/ui-build/src/components/toolbar/ToolbarContainer.vue

feat: text-align in text component #193

---

libs/frontend/feature-render-builder/src/components/SvgEdit.vue
libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts
libs/frontend/feature-render-builder/src/lib/render-builder.ts
libs/frontend/ui-build/src/components/BuildContent.vue

Close #207 
Close #208 
@abemscac I still see the absolute positioned image jump around, thought it's better than before and the SVG problem seems to be fixed. I'll merge this for now, but we might need to come back to this one!
https://github.com/samatechtw/pubstudio-builder/assets/550982/09431927-f68a-448a-b2d3-305304fcd928

207 absolute position bugs

---

apps/builder-demo/src/translations/en.json
libs/frontend/feature-build/src/lib/style/use-edit-component-child-styles.ts
libs/frontend/feature-build/src/lib/style/use-edit-component-styles.ts
libs/frontend/feature-build/src/lib/style/use-reusable-style-menu.ts
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/util-component/src/lib/compute-component-flattened-styles.ts
libs/shared/type-site/src/lib/i-style.ts

205 pseudo style inherited

---

apps/builder-demo/src/app/components/ExampleBuilder.vue
apps/builder-demo/src/translations/en.json
apps/web-site/src/app/components/NotFound.vue
backend/lib-shared-site-api/src/util/json_extractor.rs
libs/frontend/ui-widgets/src/lib/modal/Modal.vue
libs/frontend/ui-widgets/src/lib/modal/SiteErrorModal.vue
libs/frontend/ui-widgets/src/lib/modal/SiteSaveErrorModal.vue

212 site not found

---

libs/frontend/feature-build/src/lib/style/use-edit-component-child-styles.ts
libs/frontend/feature-build/src/lib/style/use-reusable-style-menu.ts
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-build/src/lib/use-history.ts
libs/frontend/feature-build/src/lib/use-toolbar.ts
libs/frontend/ui-build/src/components/toolbar/ToolbarContainer.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarText.vue
libs/frontend/util-command/src/lib/edit-styles-data.ts
libs/frontend/util-command/src/lib/replace-last-command.ts
tools/scripts/generate-default-site.ts

fix: command save issues #215

---

libs/frontend/util-edit-text/src/lib/text-to-link-keymap.ts

fix: url regex matches price string

---

.github/workflows/pr-commit.yml
libs/frontend/feature-render-builder/src/components/SvgEdit.vue
libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts
libs/frontend/feature-render-builder/src/lib/render-builder.ts
libs/frontend/ui-build/src/components/BuildContent.vue
libs/frontend/ui-build/src/components/BuildDndOverlay.vue

164 selection border affect layout 2

---

apps/builder-demo/src/translations/en.json
libs/frontend/ui-build/src/components/build-menu/BuildMenuNew.vue
libs/frontend/util-builtin/src/index.ts
libs/frontend/util-builtin/src/lib/components/builtin-components.ts
libs/frontend/util-builtin/src/lib/components/builtin-divider.ts
libs/frontend/util-builtin/src/lib/resolve-style.ts
libs/frontend/util-ids/src/lib/builtin-ids.ts
libs/frontend/util-ids/src/lib/builtin-theme-variables.ts

feat: horizontal and vertical divider builtins #224

---

libs/frontend/feature-render-builder/src/components/LinkTooltip.vue
libs/frontend/ui-build/src/components/MenuRow.vue
libs/frontend/ui-build/src/components/component-menu/ComponentEventEdit.vue
libs/frontend/ui-build/src/components/component-menu/ComponentInputEdit.vue
libs/frontend/ui-build/src/components/component-menu/ComponentInputRow.vue
libs/frontend/ui-build/src/components/component-menu/ComponentInputs.vue
libs/frontend/ui-build/src/components/page-menu/PageMenuView.vue
libs/shared/type-site/src/lib/i-component.ts

feat: show checkbox for boolean args

---

libs/frontend/ui-build/src/components/StyleRow.vue

feat: ui for setting background image style

---

libs/frontend/feature-build/src/lib/build-command-helpers.ts
libs/frontend/feature-build/src/lib/style/set-style-helpers.ts
libs/frontend/feature-build/src/lib/style/use-reusable-style-menu.ts
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/ui-build/src/components/StyleMenuEdit.vue

fix: editing mixin name change bug #232

Deploy to prod

---

backend/lib-shared-site-api/src/clients/s3_client.rs

Related to https://github.com/samatechtw/pubstudio/issues/963

fix: add error logs to s3_client #963

---

apps/builder-demo/src/translations/en.json
libs/frontend/feature-build/src/lib/build-command-helpers.ts
libs/frontend/feature-build/src/lib/style/use-reusable-style-menu.ts
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-build/src/lib/use-copy-paste.spec.ts
libs/frontend/ui-build/src/components/build-menu/BuildMenuNew.vue
libs/frontend/util-builtin/src/lib/components/builtin-components.ts
libs/frontend/util-builtin/src/lib/components/builtin-image.ts
libs/frontend/util-builtin/src/lib/resolve-style.ts
libs/frontend/util-command/src/lib/component/add-component.ts
libs/frontend/util-component/src/lib/detach-component.ts
libs/frontend/util-ids/src/lib/builtin-ids.ts

feat: builtin captioned image component #70

---

backend/lib-shared-site-api/src/clients/s3_client.rs
backend/site-api/src/app/backup/backup_sites.rs
backend/site-api/src/db/site_repo.rs

Close https://github.com/samatechtw/pubstudio/issues/963

fix: site backups not working in stg #963

---

libs/frontend/feature-render-builder/src/components/LinkTooltip.vue
libs/frontend/ui-build/src/components/build-menu/BuildMenuFile.vue
libs/frontend/ui-theme/src/css/layout.postcss
libs/frontend/util-site-deserialize/src/lib/replace-namespace.ts

fix: update relative links when template loaded #233

---

libs/frontend/util-component/src/lib/detach-component.ts

fix: replace deepclone in detachComponent #264

---

apps/builder-demo/src/translations/en.json
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-site-store-init/src/lib/use-api-store.ts
libs/frontend/feature-sites/src/lib/use-sites.ts
libs/frontend/ui-build/src/components/build-menu/BuildMenuFile.vue

feat: update site id in settings #248

---

libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/util-command/src/lib/edit-styles-data.ts

fix: edit style tab bug #267

---

libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts
libs/frontend/feature-render-builder/src/lib/dnd/drag-drop.ts
libs/frontend/feature-render-builder/src/lib/dnd/use-drag-drop.ts

fix: drag and drop image bugs #274

---

libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/feature-render-builder/src/lib/compute-builder-reusable-styles.ts
libs/frontend/feature-render/src/lib/get-page-style.ts
libs/frontend/feature-render/src/lib/use-render.ts
libs/frontend/ui-build/src/components/BuildDndOverlay.vue
libs/frontend/ui-build/src/components/component-menu/ComponentMenuMixins.vue
libs/frontend/ui-theme/src/css/layout.postcss

fix: breakpoint styles incorrect in editor #273

---

libs/frontend/util-builtin/src/lib/resolve-style.ts

fix: list builtin error #281

---

libs/frontend/ui-build/src/components/component-menu/ComponentMenu.vue
libs/frontend/util-command/src/lib/command.ts

fix: undo broken after clear history #275

---

libs/frontend/feature-site-assets/src/components/AssetCardInfoBottom.vue
libs/frontend/feature-site-assets/src/components/Assets.vue
libs/frontend/feature-site-assets/src/components/AssetsHeader.vue
libs/frontend/feature-site-assets/src/components/SelectAssetModal.vue
libs/frontend/feature-site-assets/src/lib/use-site-assets.ts
libs/frontend/ui-build/src/components/build-menu/BuildMenuAsset.vue

fix: site asset improvements #291

---

libs/shared/util-test/.eslintrc.json
libs/shared/util-test/README.md
libs/shared/util-test/jest.config.ts
libs/shared/util-test/project.json
libs/shared/util-test/src/index.ts
libs/shared/util-test/src/lib/get-site-capacity.ts
libs/shared/util-test/tsconfig.json
libs/shared/util-test/tsconfig.spec.json
tsconfig.base.json

Related to https://github.com/samatechtw/pubstudio/issues/1000

fix: list-site-servers current_load incorrect #1000

---

libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-site-store/src/lib/use-site-source.ts
libs/frontend/util-command/src/lib/page/remove-page.ts

fix: site save after import bug #292

---

apps/builder-demo/src/app/components/ExampleBuilder.vue
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-color-picker/src/components/ColorPicker.vue
libs/frontend/feature-color-picker/src/lib/color-picker-util.ts
libs/frontend/feature-render-builder/src/components/LinkTooltip.vue
libs/frontend/feature-render-builder/src/lib/dnd/use-drag-drop.ts
libs/frontend/feature-render-builder/src/lib/use-render-builder.ts
libs/frontend/feature-render/src/lib/use-render.ts
libs/frontend/feature-site-assets/src/components/AssetCard.vue
libs/frontend/feature-site-assets/src/components/CreateAssetModal.vue
libs/frontend/feature-site-store-init/src/lib/use-api-store.ts
libs/frontend/feature-site-store-init/src/lib/use-local-store.ts
libs/frontend/ui-build/src/components/theme-menu/ThemeMenuTabs.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarContainer.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarText.vue
libs/frontend/ui-theme/src/css/layout.postcss
libs/frontend/util-command-data/src/index.ts
libs/frontend/util-command-data/src/lib/add-asset-data.ts
libs/frontend/util-command/src/lib/component/add-component.spec.ts
libs/frontend/util-command/src/lib/component/add-component.ts
libs/frontend/util-command/src/lib/editor-helpers.ts
libs/frontend/util-component/src/lib/detach-component.ts
libs/frontend/util-render/src/lib/util-render.ts
package.json
pnpm-lock.yaml

fix: ui improvements 240206 #305

---

apps/builder-demo/src/translations/en.json
libs/frontend/feature-build/src/lib/use-toolbar.ts
libs/frontend/feature-render-builder/src/components/LinkTooltip.vue
libs/frontend/feature-render-builder/src/components/ProseMirrorEditor.ts
libs/frontend/ui-widgets/src/lib/form/PSInput.vue
libs/frontend/util-edit-text/src/lib/keymap.ts
libs/frontend/util-edit-text/src/lib/parse-links-during-paste.ts
libs/frontend/util-edit-text/src/lib/prosemirror-utils.ts
libs/frontend/util-edit-text/src/lib/schema-text.ts
libs/frontend/util-edit-text/src/lib/text-to-link-keymap.ts

feat: improve prosemirror links #310

---

libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts

fix: prosemirror select drag and drop

---

libs/frontend/feature-render-builder/src/lib/dnd/use-drag-drop.ts
libs/frontend/ui-build/src/components/BuildDndOverlay.vue

fix: drag drop into container red outline

---

libs/frontend/ui-widgets/src/lib/InfoBubble.vue
libs/frontend/util-tooltip/src/index.ts
libs/frontend/util-tooltip/src/lib/use-info-bubble.ts

fix: info bubble improvements #48

---

libs/frontend/feature-build/src/lib/build-command-helpers.ts
libs/frontend/feature-build/src/lib/style/use-edit-styles.ts
libs/frontend/feature-build/src/lib/use-toolbar.ts
libs/frontend/ui-build/src/components/build-menu/BuildMenuFile.vue
libs/frontend/ui-build/src/components/component-menu/ComponentStyles.vue
libs/frontend/ui-build/src/components/component-menu/SizeInput.vue
libs/frontend/util-command/src/lib/create-site.ts

fix: override mixin property and undo #266

---

libs/frontend/feature-build/src/lib/use-theme-colors.ts
libs/frontend/feature-build/src/lib/use-theme-menu-variables.ts
libs/frontend/feature-color-picker/src/components/ColorPicker.vue
libs/frontend/ui-build/src/components/MenuRow.vue
libs/frontend/ui-build/src/components/theme-menu/ThemeMenu.vue
libs/frontend/ui-build/src/components/theme-menu/ThemeVariableEdit.vue
libs/frontend/ui-build/src/components/theme-menu/ThemeVariableFont.vue
libs/frontend/ui-build/src/components/theme-menu/ThemeVariableList.vue
libs/frontend/ui-build/src/components/theme-menu/ThemeVariables.vue
libs/frontend/util-doc/src/lib/is-color.ts
libs/shared/type-site/src/lib/i-theme.ts

feat: font and color picker for theme vars #306

---

apps/api-site-test/test/integration/update-site-metadata.spec.ts
backend/lib-shared-types/src/dto/site_api/site_metadata_viewmodel.rs
backend/site-api/src/app/site/list_sites.rs
backend/site-api/src/app/site/update_site_metadata.rs
backend/site-api/src/db/sites_metadata_repo.rs
libs/shared/type-api-platform-site/src/lib/i-update-platform-site-api-request.ts
libs/shared/type-api-shared/.eslintrc.json
libs/shared/type-api-shared/README.md
libs/shared/type-api-shared/jest.config.ts
libs/shared/type-api-shared/project.json
libs/shared/type-api-shared/src/index.ts
libs/shared/type-api-shared/src/lib/enum-site-checkout-state.ts
libs/shared/type-api-shared/tsconfig.json
libs/shared/type-api-shared/tsconfig.lib.json
libs/shared/type-api-shared/tsconfig.spec.json
libs/shared/type-api-site-sites/src/lib/i-list-sites-api-response.ts
libs/shared/type-api-site-sites/src/lib/i-update-site-metadata-api-request.ts
tsconfig.base.json

Related to https://github.com/samatechtw/pubstudio/issues/1043

feat: adjust update-site-metadata endpoint for migrations #1043

---

apps/web-site/src/app/App.vue
libs/frontend/ui-build/src/components/preview/SitePreview.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarContainer.vue
libs/frontend/ui-theme/src/css/components/app.postcss
libs/frontend/ui-theme/src/css/components/prosemirror-view.postcss

fix: prosemirror edit bugs #261

---

apps/api-site-test/test/integration/list-site-versions.spec.ts
apps/api-site-test/test/integration/publish-site.spec.ts
backend/lib-shared-types/src/dto/query_dto.rs
backend/lib-shared-types/src/dto/site_api/publish_site_dto.rs
backend/lib-shared-types/src/dto/site_api/update_site_dto.rs
backend/site-api/src/app/publish/publish_site.rs
backend/site-api/src/db/site_repo.rs
libs/shared/type-api-site-sites/src/lib/i-publish-site-api-request.ts

feat: modify publish endpoint for drafts #346

---

libs/frontend/feature-site-translations/src/components/TranslationsModal.vue
libs/frontend/feature-site-translations/src/lib/use-site-translations.ts

fix: translations should not be wrapped with a div

---

apps/api-site-test/test/integration/create-draft.spec.ts
apps/api-site-test/test/integration/list-site-versions.spec.ts
apps/api-site-test/test/integration/publish-site.spec.ts
backend/site-api/src/app/app_router.rs
backend/site-api/src/app/publish/create_draft.rs
backend/site-api/src/app/publish/mod.rs
backend/site-api/src/app/site/update_site.rs
backend/site-api/src/db/site_repo.rs

feat: add create-draft endpoint #349

---

apps/api-site-test/test/integration/create-draft.spec.ts
apps/api-site-test/test/integration/get-current-site.spec.ts
backend/lib-shared-site-api/src/cache/cache.rs
backend/lib-shared-types/src/dto/site_api/get_current_site_dto.rs
backend/site-api/src/app/admin/reset_all.rs
backend/site-api/src/app/publish/publish_site.rs
backend/site-api/src/app/site/create_site.rs
backend/site-api/src/app/site/get_current_site.rs
backend/site-api/src/app/site/update_site.rs
backend/site-api/src/app/usage/reset_cache.rs
backend/site-api/src/db/cache_helpers.rs
backend/site-api/src/middleware/auth.rs

fix: publish site cache bug #368

---

libs/frontend/feature-render-builder/src/components/ProseMirrorEditor.ts

fix: component selection broken after scroll #312

---

backend/lib-shared-site-api/src/clients/s3_client.rs
backend/site-api/src/app/backup/backup_all.rs
backend/site-api/src/app/backup/backup_sites.rs
backend/site-api/src/app/backup/create_backup.rs
backend/site-api/src/app/backup/delete_backup.rs
backend/site-api/src/app/backup/helpers.rs
backend/site-api/src/app/backup/restore_backup.rs

feat: disable backups when S3 env is not present #6

---

libs/frontend/feature-build/src/lib/style/use-edit-component-child-styles.ts
libs/frontend/feature-build/src/lib/style/use-reusable-style-menu.ts
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/util-component/src/lib/compute-component-flattened-styles.ts
libs/frontend/util-component/src/lib/find-styles.ts

fix: incorrect style precedence in editor

---

backend/lib-shared-types/src/dto/site_api/custom_data_dto.rs
backend/lib-shared-types/src/dto/site_api/custom_metadata_viewmodel.rs
backend/lib-shared-types/src/dto/site_api/mod.rs
backend/site-api/db/sites/migrations/20240314153500_custom_data_info.sql
backend/site-api/src/api_context.rs
backend/site-api/src/app/app_router.rs
backend/site-api/src/app/custom/add_column.rs
backend/site-api/src/app/custom/add_row.rs
backend/site-api/src/app/custom/create_table.rs
backend/site-api/src/app/custom/custom_data.rs
backend/site-api/src/app/custom/list_rows.rs
backend/site-api/src/app/custom/list_tables.rs
backend/site-api/src/app/custom/mod.rs
backend/site-api/src/app/custom/modify_column.rs
backend/site-api/src/app/custom/remove_column.rs
backend/site-api/src/app/custom/update_row.rs
backend/site-api/src/app/mod.rs
backend/site-api/src/db/custom_data_repo.rs
backend/site-api/src/db/mod.rs
backend/site-api/src/db/site_db_pool_manager.rs
backend/site-api/src/db/site_repo.rs
backend/site-api/src/main.rs

Close https://github.com/samatechtw/pubstudio/issues/1077

feat: api action endpoint scaffolding (types, db) #1077

---

libs/frontend/feature-site-store/src/lib/use-site-source.ts
libs/frontend/ui-build/src/components/build-menu/BuildMenuNew.vue

Close https://github.com/samatechtw/pubstudio/issues/1115

feat: hide contact form in identity/scratch site

---

libs/frontend/feature-build/src/lib/use-edit-component-event.ts
libs/frontend/ui-build/src/components/component-menu/BehaviorModal.vue
libs/frontend/ui-build/src/components/component-menu/ComponentEventEdit.vue
libs/frontend/ui-build/src/components/component-menu/ComponentMenu.vue

feat: add new behavior to editing event #416

---

libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts
libs/frontend/feature-render-builder/src/lib/render-builder.ts

fix: drag/drop input and textarea improvements #413

---

libs/frontend/feature-build/src/lib/use-css-size.ts
libs/frontend/feature-site-store/src/lib/use-site-source.ts
libs/frontend/ui-build/src/components/component-menu/SizeInput.vue
libs/frontend/ui-widgets/src/lib/SizeUnit.vue
libs/frontend/ui-widgets/src/lib/toolbar/ToolbarFlexBasis.vue

feat: update unit when percent typed #414

---

libs/frontend/feature-build/src/lib/use-css-size.ts
libs/frontend/ui-build/src/components/component-menu/SizeInput.vue

fix: remove min and max height ui #429

---

apps/api-site-test/test/custom/add-row.spec.ts
backend/lib-shared-types/src/error/api_error.rs
backend/site-api/src/app/custom/add_row.rs
backend/site-api/src/db/custom_data_repo.rs

fix: add row error with certain characters #431

---

backend/site-api/src/app/site/get_site_usage.rs
libs/frontend/feature-render/src/lib/setup-routes.ts
libs/frontend/util-router/src/lib/create-router.ts
libs/frontend/util-router/src/lib/i-route.ts
libs/frontend/util-router/src/lib/i-router.ts

feat: no home redirect #454

---

libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/feature-build-event/src/lib/util-build-event.ts
libs/frontend/ui-build/src/components/build-menu/BuildMenuFile.vue
libs/frontend/ui-build/src/components/toolbar/SiteToolbar.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarBreakpoint.vue
libs/frontend/ui-widgets/src/lib/modal/Modal.vue

fix: disable editor hotkeys when modal open #1152

---

libs/frontend/data-access-command/src/lib/component/add-component.ts
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-render/src/lib/render-helpers.ts
libs/frontend/feature-site-version/src/lib/use-site-version.ts
libs/frontend/ui-build/src/components/theme-menu/ThemeFonts.vue
libs/frontend/ui-build/src/components/toolbar/SiteToolbar.vue
libs/frontend/ui-theme/src/css/layout.postcss
libs/frontend/ui-widgets/src/lib/SizeUnit.vue
libs/frontend/ui-widgets/src/lib/toolbar/ToolbarItem.vue

fix: editor ui bugs #451

---

libs/frontend/feature-build-event/src/lib/util-build-event.ts
libs/frontend/feature-render-builder/src/lib/render-builder.ts
libs/frontend/feature-render/src/lib/compute-attrs-inputs-mixins.ts
libs/frontend/ui-build/src/components/component-menu/ComponentInputs.vue

Close #467 
Show placeholder in builder input/textarea
Fix build event disabled in input/textarea

feat: show inherited reusable inputs #467

---

libs/frontend/feature-build/src/index.ts
libs/frontend/feature-build/src/lib/command-wrap/move-component.ts
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-render-builder/src/lib/dnd/use-drag-drop.ts
libs/frontend/ui-build/src/components/toolbar/SiteToolbar.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarBuilderWidth.vue

fix: drag drop absolute component scale #458

---

libs/frontend/feature-render-builder/src/lib/render-builder.ts
libs/frontend/util-router/src/components/RouterLink.vue

507 mailto link bug

---

libs/frontend/feature-build-event/src/lib/hotkey-actions.ts
libs/frontend/ui-widgets/src/lib/UsageProgress.vue

515 reset selected component

---

apps/api-site-test/test/integration/get-site-metadata.spec.ts
libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/feature-render-builder/src/lib/render-builder.ts

fix: svg offset in builder #503

---

libs/frontend/feature-build/src/lib/use-build.ts

fix: flatten mixin overwrite style bug #511

---

libs/frontend/data-access-command/src/lib/edit-styles-data.ts
libs/frontend/data-access-command/src/lib/editor-helpers.ts
libs/frontend/feature-breakpoint/src/lib/use-breakpoint.ts
libs/frontend/feature-build/src/lib/style/use-edit-component-child-styles.ts
libs/frontend/feature-build/src/lib/style/use-edit-component-styles.ts
libs/frontend/feature-build/src/lib/style/use-edit-styles.ts
libs/frontend/feature-build/src/lib/style/use-mixin-menu.ts
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-build/src/lib/use-toolbar.ts
libs/frontend/feature-render-builder/src/lib/compute-builder-mixins.ts
libs/frontend/feature-render-builder/src/lib/get-build-page-style.ts
libs/frontend/feature-site-store/src/lib/use-site-source.ts
libs/frontend/ui-build/src/components/component-menu/ComponentStyles.vue
libs/frontend/ui-build/src/components/style-menu/StyleMenuEdit.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarBreakpoint.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarBreakpointOption.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarPseudoClass.vue

fix: edit mixin pseudo/breakpoint bug #510

---

libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-builtin/src/lib/behaviors.ts
libs/frontend/feature-render-builder/src/components/BuilderEdit.vue
libs/frontend/feature-render-builder/src/components/VueEdit.vue
libs/frontend/ui-build/src/components/component-menu/BehaviorModal.vue
libs/frontend/ui-build/src/components/component-menu/ComponentEventEdit.vue
libs/frontend/util-builtin/src/lib/components/builtin-button.ts
libs/frontend/util-resolve/src/lib/behavior-helpers.ts
libs/frontend/util-resolve/src/lib/resolve-behavior.ts
libs/shared/type-site/src/lib/i-resolved-behavior.ts

edit behavior bugs

---

backend/lib-shared-types/src/shared/site_asset.rs
libs/frontend/feature-site-assets/src/components/AssetCard.vue
libs/frontend/feature-site-assets/src/components/CreateAssetModal.vue
libs/frontend/ui-widgets/src/index.ts
libs/frontend/ui-widgets/src/lib/svg/Wasm.vue
libs/frontend/util-asset/src/lib/format-asset-url.ts
libs/frontend/util-validate/src/lib/validate-media.ts
libs/shared/type-api-platform-site-asset/src/lib/asset-content-type.ts
libs/shared/util-format/src/lib/util-format.ts

feat: support wasm filetype for asset upload #538

---

libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts
libs/frontend/feature-site-version/src/lib/use-site-version.ts
libs/frontend/ui-build/src/components/component-menu/BehaviorArgs.vue
libs/frontend/ui-build/src/components/preview/SitePreview.vue
libs/frontend/ui-theme/src/css/components/app.postcss
libs/frontend/ui-theme/src/css/components/content.postcss
libs/frontend/ui-theme/src/css/components/menu.postcss
libs/frontend/ui-theme/src/css/components/modal.postcss
libs/frontend/ui-theme/src/css/components/multiselect.postcss
libs/frontend/util-key-listener/src/lib/key-listener.ts
libs/frontend/util-site-deserialize/src/lib/replace-namespace.ts

Close #531 
Close #532 
Close #533

531 builder preview default styles bug

---

libs/frontend/ui-build/src/components/component-menu/ComponentDimensions.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarPage.vue

fix: toolbar page dropdown ordering #537

---

libs/frontend/feature-build/src/lib/link-datalist-options.ts
libs/frontend/feature-build/src/lib/use-page-menu.ts
libs/frontend/ui-build/src/components/overlay/BuildDndOverlay.vue

fix: page bugs #547

---

apps/api-site-test/test/integration/get-site-metadata.spec.ts
apps/api-site-test/test/integration/update-site-metadata.spec.ts
backend/lib-shared-types/src/dto/site_api/site_metadata_viewmodel.rs
backend/lib-shared-types/src/dto/site_api/update_metadata_dto.rs
backend/lib-shared-types/src/entity/site_api/site_metadata_entity.rs
backend/site-api/src/app/site/get_site_metadata.rs
backend/site-api/src/app/site/list_sites.rs
backend/site-api/src/app/site/update_site_metadata.rs
backend/site-api/src/db/sites_metadata_repo.rs
libs/frontend/util-builtin/src/lib/components/builtin-header.ts
libs/shared/type-api-site-sites/src/lib/i-list-sites-api-response.ts
libs/shared/type-api-site-sites/src/lib/i-update-site-metadata-api-request.ts

feat: update site metadata owner id #557

---

libs/frontend/ui-build/src/components/theme-menu/ThemeMetaEditModal.vue
libs/shared/type-site/src/lib/enum-tag.ts
libs/shared/type-site/src/lib/i-head.ts

feat: add canvas tag #564

---

docs/events-inputs-behaviors.md
libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/feature-render/src/lib/custom-event-handlers.ts
libs/frontend/ui-build/src/components/ComponentTreeItem.vue
libs/frontend/util-runtime/src/lib/runtime-context.ts
libs/shared/type-site/src/lib/enum-component-event-type.ts
libs/shared/type-site/src/lib/enum-css.ts

Close #568 
Close #569 
Close #570

568 css clip path

---

backend/lib-shared-types/src/shared/site_asset.rs
libs/frontend/feature-build/src/lib/use-select-asset.ts
libs/frontend/ui-build/src/components/StyleRow.vue
libs/frontend/ui-build/src/components/preview/PreviewBanner.vue
libs/frontend/util-asset/src/lib/format-asset-url.ts
libs/shared/type-api-platform-site-asset/src/lib/asset-content-type.ts
libs/shared/util-format/src/lib/util-format.ts

feat: support for uploading svgs to object storage #581

---

backend/lib-shared-types/src/shared/site_asset.rs
libs/frontend/feature-build/src/lib/use-select-asset.ts
libs/frontend/util-asset/src/lib/format-asset-url.ts
libs/frontend/util-fields/src/lib/admin-field-gen.ts
libs/shared/type-api-platform-site-asset/src/lib/asset-content-type.ts
libs/shared/util-format/src/lib/util-format.ts

feat: support webp in object storage #593

---

libs/frontend/data-access-command/src/lib/component-custom-style/set-component-custom-style.ts
libs/frontend/data-access-command/src/lib/set-selected-component.ts
libs/frontend/feature-build/src/lib/build-command-helpers.ts
libs/frontend/feature-build/src/lib/style/set-style-helpers.ts
libs/frontend/feature-build/src/lib/style/use-edit-component-styles.ts
libs/frontend/feature-build/src/lib/use-build.ts
libs/shared/type-command-data/src/lib/component/i-set-component-custom-style-data.ts
libs/shared/type-site/src/lib/enum-css.ts

fix: set position select parent bug #589

---

libs/frontend/util-builtin/src/lib/components/builtin-footer.ts

feat: improve footer builtin #592

---

libs/frontend/feature-render-builder/src/lib/use-render-builder.ts

fix: show global styles in prosemirror editor #580

---

apps/api-site-test/test/custom/update-row.spec.ts
backend/site-api/src/app/custom/custom_data.rs
libs/frontend/util-resolve/src/lib/behavior-helpers.ts
libs/frontend/util-router/src/lib/router-helpers.ts
libs/shared/type-site/src/lib/i-resolved-behavior.ts

632 update row behavior helper

---

apps/api-site-test/test/custom/update-row.spec.ts
backend/site-api/src/app/custom/add_row.rs
backend/site-api/src/app/custom/update_row.rs
backend/site-api/src/app/custom/validate_row_data.rs
backend/site-api/src/db/custom_data_repo.rs

fix: row validation fixes and testing #638

---

libs/frontend/feature-preview/src/lib/merge-search.ts
libs/frontend/feature-preview/src/lib/route-to-preview-path.ts

fix: preview site link search params #645

---

apps/api-site-test/test/custom/add-row.spec.ts
apps/api-site-test/test/custom/delete-table.spec.ts
apps/api-site-test/test/custom/modify-column.spec.ts
backend/lib-shared-types/src/dto/custom_data/custom_data_dto.rs
backend/lib-shared-types/src/dto/custom_data/delete_table_dto.rs
backend/lib-shared-types/src/dto/custom_data/mod.rs
backend/site-api/src/app/custom/add_row.rs
backend/site-api/src/app/custom/custom_data.rs
backend/site-api/src/app/custom/delete_table.rs
backend/site-api/src/app/custom/helpers.rs
backend/site-api/src/app/custom/mod.rs
backend/site-api/src/app/custom/modify_column.rs
backend/site-api/src/app/custom/validate_row_data.rs
backend/site-api/src/db/custom_data_info_repo.rs
backend/site-api/src/db/custom_data_repo.rs
libs/frontend/data-access-api/src/lib/api-custom-data.ts
libs/frontend/feature-custom-data/src/components/CustomDataModal.vue
libs/frontend/feature-custom-data/src/components/DeleteTableModal.vue
libs/frontend/feature-custom-data/src/components/ExportTableModal.vue
libs/frontend/feature-custom-data/src/lib/use-data-table.ts
libs/frontend/feature-custom-data/src/lib/use-export-table.ts
libs/shared/type-api-interfaces/src/lib/api-interfaces.ts
libs/shared/type-api-site-custom-data/src/index.ts
libs/shared/type-api-site-custom-data/src/lib/enum-custom-data-action.ts
libs/shared/type-api-site-custom-data/src/lib/i-delete-table-api-request.ts

feat: delete custom table #636

---

libs/frontend/ui-build/src/components/theme-menu/ThemeVariableFont.vue
libs/frontend/util-render/src/lib/util-render.ts
package.json

fix: adjust font family fallback behavior #646

---

apps/web-site/src/app/App.vue
backend/site-api/src/db/custom_data_repo.rs
backend/site-api/src/main.rs
libs/frontend/util-runtime/src/lib/runtime-context.ts

fix: live mode scroll event #653

---

libs/frontend/feature-build/src/index.ts
libs/frontend/feature-build/src/lib/command-wrap/group.ts
libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts
libs/frontend/feature-render/src/lib/render-helpers.ts
libs/frontend/feature-site-translations/src/components/ConvertTranslations.vue
libs/frontend/feature-site-translations/src/components/TranslationsModal.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarContainer.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarText.vue
libs/frontend/util-render/src/lib/util-render.ts
package.json
pnpm-lock.yaml

feat: convert site text to i18n #662

---

apps/api-site-test/test/integration/get-current-site.spec.ts
apps/api-site-test/test/integration/get-public-site-usage.spec.ts
apps/api-site-test/test/integration/get-site-usage.spec.ts
apps/api-site-test/test/integration/persist-usage.spec.ts
backend/lib-shared-site-api/src/cache/cache.rs
backend/lib-shared-site-api/src/cache/cache_helpers.rs
backend/lib-shared-types/src/cache/site_usage_data.rs
backend/lib-shared-types/src/dto/site_api/site_usage_viewmodel.rs
backend/lib-shared-types/src/entity/site_api/site_usage_entity.rs
backend/site-api/src/app/admin/reset_all.rs
backend/site-api/src/app/usage/helpers.rs
backend/site-api/src/app/usage/reset_cache.rs
backend/site-api/src/cron.rs
backend/site-api/src/db/usage_repo.rs
backend/site-api/src/main.rs
libs/frontend/util-builtin/src/lib/builtin-behaviors.ts
libs/shared/type-api-site-sites/src/lib/i-get-site-usage-api-response.ts

feat: improve site usage tracking #699

---

apps/web-site/src/app/App.vue
libs/frontend/feature-build/src/lib/add-builtin/add-builtin-component.ts
libs/frontend/feature-render-builder/src/lib/render-builder.ts
libs/frontend/feature-render/src/lib/render-helpers.ts
libs/frontend/ui-build/src/components/BuildContent.vue
libs/frontend/util-builtin/src/lib/builtin-behaviors.ts

fix: various builder bugs #702

---

libs/frontend/data-access-command/src/lib/breakpoint/set-breakpoint.spec.ts
libs/frontend/data-access-command/src/lib/breakpoint/set-breakpoint.ts
libs/frontend/data-access-state/src/lib/misc-store.ts
libs/frontend/ui-build/src/components/build-menu/BuildMenu.vue
libs/frontend/ui-build/src/components/build-menu/BuildMenuHistory.vue
libs/frontend/ui-build/src/components/build-menu/BuildMenuNew.vue

fix: various bugs #713

---

libs/frontend/feature-build/src/lib/use-build.ts
libs/frontend/feature-build/src/lib/use-copy-paste.ts
libs/frontend/feature-render-builder/src/components/ProseMirrorEditor.ts
libs/frontend/ui-build/src/components/component-menu/ComponentMenu.vue
libs/frontend/util-site-deserialize/src/lib/replace-namespace.ts
libs/shared/type-site/src/lib/i-editor-context.ts
libs/shared/type-site/src/lib/i-serialized-site.ts

471 split text component

---

libs/frontend/feature-site-assets/src/components/AssetCard.vue
libs/frontend/feature-site-assets/src/components/AssetCardDropdown.vue
libs/frontend/feature-site-assets/src/components/AssetCardImage.vue
libs/frontend/feature-site-assets/src/components/AssetCardInfoBottom.vue
libs/frontend/feature-site-assets/src/components/AssetCardSmall.vue
libs/frontend/feature-site-assets/src/components/Assets.vue
libs/frontend/feature-site-assets/src/index.ts
libs/frontend/feature-site-assets/src/lib/use-build-menu-assets.ts
libs/frontend/ui-build/src/components/build-menu/BuildMenuAsset.vue
libs/frontend/ui-build/src/components/preview/SitePreview.vue
libs/frontend/util-router/src/components/RouterLink.ts

feat: asset actions in build left menu #629

---

libs/frontend/feature-build/src/lib/use-copy-paste.ts
libs/frontend/feature-site-assets/src/components/AssetCard.vue
libs/frontend/feature-site-assets/src/components/CreateAssetModal.vue
libs/frontend/ui-build/src/components/component-menu/BehaviorArgs.vue
libs/frontend/ui-build/src/components/toolbar/SiteToolbar.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarPseudoClass.vue
libs/frontend/ui-widgets/src/lib/form/SimpleFileUpload.vue
libs/frontend/util-builtin/src/lib/builtin-behaviors.ts
libs/frontend/util-render/src/lib/iterate-page.ts
libs/frontend/util-resolve/src/index.ts
libs/frontend/util-resolve/src/lib/behavior-helpers.ts
libs/frontend/util-resolve/src/lib/find-component.ts
libs/shared/type-site/src/lib/i-resolved-behavior.ts

fix: various builder bugs #727

---

apps/api-site-test/test/backup/backup-all.spec.ts
apps/api-site-test/test/custom/modify-column.spec.ts
backend/lib-shared-types/src/error/api_error.rs
backend/site-api/src/app/backup/backup_sites.rs
backend/site-api/src/app/custom/helpers.rs
backend/site-api/src/app/custom/modify_column.rs
backend/site-api/src/db/backup_repo.rs
libs/frontend/feature-contact-form/src/lib/use-contact-form.ts
libs/frontend/feature-custom-data/src/components/CustomDataModal.vue
libs/frontend/feature-custom-data/src/components/CustomDataTable.vue
libs/frontend/feature-custom-data/src/components/CustomDataTableHead.vue
libs/frontend/feature-custom-data/src/components/EditTableRow.vue
libs/frontend/feature-mailing-list-form/src/lib/use-mailing-list-form.ts
libs/frontend/ui-build/src/components/build-menu/BuildMenu.vue

730 custom data bugs

---

libs/frontend/data-access-command/src/lib/component/remove-component.spec.ts
libs/frontend/data-access-command/src/lib/create-site.ts
libs/frontend/data-access-command/src/lib/set-selected-component.ts
libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/ui-build/src/components/ComponentTreeItem.vue
libs/frontend/ui-build/src/components/ComponentTreeItemRename.vue
libs/frontend/util-builder/src/lib/builder-context.ts
libs/frontend/util-runtime/src/lib/runtime-context.ts
libs/frontend/util-site-deserialize/src/lib/deserialize-site.ts
libs/frontend/util-site-store/src/lib/serialize-site.ts
libs/frontend/util-test-mock/src/lib/mock-site-data.ts
libs/frontend/util-test/src/lib/expect-site-without-component-tree.ts
libs/shared/type-site/src/lib/i-editor-context.ts

fix: component menu rename bugs and refactor #504

---

libs/frontend/data-access-command/src/lib/component-tree-item-util.ts
libs/frontend/data-access-command/src/lib/set-selected-component.ts
libs/frontend/ui-build/src/components/ComponentTreeItem.vue

feat: component menu expand/collapse all #54

---

libs/frontend/feature-build-overlay/src/components/BuildDndOverlay.vue
libs/frontend/feature-build-overlay/src/components/HoverEdges.vue
libs/frontend/feature-build-overlay/src/lib/compute-selection-overlay.ts
libs/frontend/feature-build-overlay/src/lib/feature-build-overlay.ts
libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts
libs/frontend/feature-render-builder/src/lib/dnd/use-drag-drop.ts
libs/frontend/feature-render-builder/src/lib/render-builder.ts
libs/frontend/ui-build/src/components/ComponentTree.vue
libs/frontend/ui-build/src/components/ComponentTreeItem.vue
libs/frontend/ui-build/src/components/preferences/PreferenceGeneral.vue
libs/frontend/ui-build/src/components/preferences/PreferenceRow.vue
libs/frontend/util-builder/src/lib/default-editor-prefs.ts
libs/shared/type-site/src/lib/i-editor-context.ts
package.json
pnpm-lock.yaml

752 component drag drop

---

libs/frontend/ui-build/src/components/preview/SitePreview.vue

fix: preview text component newlines #759

---

libs/frontend/feature-build-overlay/src/components/BuildDndOverlay.vue
libs/frontend/feature-build-overlay/src/components/ImageEdit.vue
libs/frontend/ui-build/src/components/preview/PreviewBanner.vue
libs/frontend/ui-build/src/components/preview/SitePreview.vue

Close #457 
The original issue was already fixed due to previous DnD changes, but a few display issues were discovered and fixed while reviewing.

fix: image issues in builder and preview #457

---

libs/frontend/data-access-api/src/lib/api-template.ts
libs/frontend/data-access-command/src/lib/set-selected-component.ts
libs/frontend/ui-build/src/components/preview/PreviewBanner.vue
libs/frontend/ui-theme/src/css/components/builder.postcss
libs/shared/type-api-platform-template/src/lib/i-template.view-model.ts

fix: various builder issues #763

---

libs/frontend/data-access-web-store/src/lib/local-update-store.ts
libs/frontend/feature-preview/src/lib/use-preview-page.ts
libs/frontend/feature-site-store-init/src/lib/use-api-store.ts

fix: multiple sites preview shows incorrectly #741

---

libs/frontend/feature-build-overlay/src/components/BuildDndOverlay.vue
libs/frontend/feature-render-builder/src/components/BuilderEdit.vue
libs/frontend/feature-render-builder/src/components/LinkTooltip.vue
libs/frontend/feature-render-builder/src/index.ts
libs/frontend/feature-render-builder/src/lib/render-builder.ts
libs/frontend/feature-render/src/lib/compute-attrs-inputs-mixins.ts
libs/frontend/ui-theme/src/css/components/builder.postcss

feat: show svg above component and clean builder #590

---

libs/frontend/feature-build-overlay/src/components/BuildDndOverlay.vue
libs/frontend/feature-render-builder/src/lib/render-builder.ts
libs/frontend/ui-build/src/components/BuildContent.vue

567 reload site tab change

---

libs/frontend/feature-build-event/src/lib/use-build-event.ts
libs/frontend/feature-build-overlay/src/components/BuildDndOverlay.vue
libs/frontend/feature-build-overlay/src/lib/feature-build-overlay.ts
libs/frontend/feature-render-builder/src/components/ProseMirrorEditor.ts
libs/frontend/util-builder/src/lib/builder-context.ts

fix: text input selection overlay bug #771

---

libs/frontend/feature-render-builder/src/components/LinkTooltip.vue

fix: prosemirror link tooltip label #512

---

libs/frontend/util-ids/src/lib/builtin-theme-variables.ts

refactor: add comment about new theme vars #552

---

apps/api-site-test/test/integration/get-public-site-usage.spec.ts
apps/api-site-test/test/integration/get-site-usage.spec.ts
apps/api-site-test/test/integration/persist-usage.spec.ts
backend/lib-shared-site-api/src/cache/cache.rs
backend/lib-shared-types/src/cache/site_usage_data.rs
backend/lib-shared-types/src/dto/site_api/site_usage_viewmodel.rs
backend/lib-shared-types/src/entity/site_api/site_usage_entity.rs
backend/site-api/db/metadata/migrations/20250502105100_usage_public_request_count.sql
backend/site-api/src/app/site/get_current_site.rs
backend/site-api/src/app/usage/helpers.rs
backend/site-api/src/db/sites_metadata_repo.rs
backend/site-api/src/db/usage_repo.rs
libs/frontend/util-builtin/src/lib/builtin-behaviors.ts
libs/shared/type-api-site-sites/src/lib/i-get-site-usage-api-response.ts

feat: split view tracking and bandwidth limiting #735

---

apps/api-site-test/test/integration/get-public-site-usage.spec.ts
apps/api-site-test/test/integration/get-site-usage.spec.ts
apps/api-site-test/test/integration/persist-usage.spec.ts
apps/web-site/src/app/App.vue
backend/lib-shared-site-api/src/cache/cache.rs
backend/lib-shared-site-api/src/db/mod.rs
backend/lib-shared-site-api/src/db/separated.rs
backend/lib-shared-types/src/cache/site_usage_data.rs
backend/lib-shared-types/src/dto/site_api/mod.rs
backend/lib-shared-types/src/dto/site_api/record_page_view_dto.rs
backend/lib-shared-types/src/dto/site_api/site_usage_viewmodel.rs
backend/lib-shared-types/src/entity/site_api/site_usage_entity.rs
backend/lib-shared-types/src/error/api_error.rs
backend/site-api/src/app/app_router.rs
backend/site-api/src/app/site/mod.rs
backend/site-api/src/app/site/record_page_view.rs
backend/site-api/src/app/usage/helpers.rs
backend/site-api/src/db/db_cache_layer.rs
backend/site-api/src/db/usage_repo.rs
libs/shared/type-api-site-sites/src/lib/i-get-site-usage-api-response.ts

feat: track individual page visits #734

---

libs/frontend/feature-copy-paste/src/lib/use-copy-paste.ts
libs/frontend/ui-widgets/src/lib/modal/ConfirmModal.vue

feat: allow pasting components as root children #779

---

libs/frontend/feature-build-overlay/src/components/ImageEdit.vue
libs/frontend/feature-site-assets/src/components/SelectAssetModal.vue
libs/frontend/feature-site-assets/src/lib/use-assets-filter.ts
libs/frontend/ui-build/src/components/StyleRow.vue
libs/frontend/ui-build/src/components/component-menu/ComponentInputs.vue
libs/frontend/ui-build/src/components/component-menu/ComponentMenu.vue
libs/frontend/ui-build/src/components/component-menu/ComponentStyles.vue
libs/frontend/ui-build/src/components/preview/SitePreview.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarColorPicker.vue
libs/frontend/ui-build/src/components/toolbar/ToolbarContainer.vue
package.json
pnpm-lock.yaml

fix: builder bugs and improvements #791
